### ISSUE TITLE
Infinite loop finded in gtvp1::gtpu when unmarshalling with an UDPPort length at zero.

### ISSUE THREAD

**Issue by Vadimador** [ErvinsK/gtp-rs#2]
Hello ! I found an infinite loop in your library. Here is some information on how to reproduce it :

### versions
- Debian GNU/Linux 11 (bullseye)
- table-x86_64-unknown-linux-gnu unchanged - rustc 1.72.0 (5680fa18f 2023-08-23)

###  To reproduce :
we clone the repository :
`
git clone https://github.com/ErvinsK/gtp-rs.git
`
we add this main.rs to gtp-rs/src :
```
use ::gtp_rs::gtpv1::gtpu::*;

fn main() {

    // we create the extension_header
    let mut ext_header = UDPPort::default();
    ext_header.length = 0; // <-- the infinite loop is probably due to the length being 0
     
    // we add it to the header
    let mut header = Gtpv1Header::default();
    header.extension_headers = Some(vec![ExtensionHeader::UDPPort(ext_header)]);
 
    let mut array:Vec<u8> = vec![];
    header.marshal(&mut array);
    let _ = Gtpv1Header::unmarshal(&array); // <-- the infinite-loop happen when we try to unmarshal
    
}

```
we build and run : 
`cargo build && cargo run`

**Comment by ErvinsK** [comment]
Issue fixed - additional check implemented to prevent the infinite loops and exit properly with an error with length is set to zero.
